version: "3"

services:

  freeswitch:
    image: freeswitch:p-host-src
    build:
      context: .
    network_mode: "host"
    volumes:
      - "./freeswitch/conf:/usr/local/freeswitch/conf"
      - "./freeswitch/scripts:/usr/local/freeswitch/scripts"
    #  - "./vanilla_conf:/opt"