FROM debian:buster
LABEL maintainer = Igor Olhovskiy <IgorOlhovskiy@gmail.com>

# Install Required Dependencies
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
        wget \
        curl \
        net-tools \
        sngrep \
        sip-tester \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY ./docker-entrypoint-sipp.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh

WORKDIR /opt

ENTRYPOINT ["/docker-entrypoint.sh"]